In [5]:
import numpy as np
import classmetho

In [44]:
from dataclasses import dataclass

@dataclass
class A:
    i: int
    s: str
    
a = A(1, 's')
b = A(1, 's')

a == b

True

In [41]:

for method_name in [
    'all',                     
    'any', 
    'argmax', 
    'argmin', 
    'argpartition',
    'argsort',
    'astype',
    'choose',
    'clip',
    'compress',
    'conj',
    'conjugate',
    'copy',
    'cumprod',
    'cumsum',
    'diagonal',
    'dump',
    'dumps',
    'fill',
    'flatten',
    'getfield',
    'item',
    'itemset',
    'max',
    'mean',
    'min',
    'newbyteorder',
    'nonzero',
    'partition',
    'prod',
    'ptp',
    'put',
    'ravel',
    'repeat',
    'reshape',
    'resize',
    'round',
    'searchsorted',
    'setfield',
    'setflags',
    'sort',
    'squeeze',
    'std',
    'sum',
    'swapaxes',
    'take',
    'tobytes',
    'tofile',
    'tolist',
    'tostring',
    'trace',
    'transpose',
    'var',
    'view',
    ]:
    print()
    print(method_name)
    a = np.arange(9).reshape((3, 3))
    try:
        method = getattr(a, method_name)
        b = method()
        print(a)
        print(b)
    except:
        pass


all
[[0 1 2]
 [3 4 5]
 [6 7 8]]
False

any
[[0 1 2]
 [3 4 5]
 [6 7 8]]
True

argmax
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8

argmin
[[0 1 2]
 [3 4 5]
 [6 7 8]]
0

argpartition

argsort
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]

astype

choose

clip

compress

conj
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

conjugate
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

copy
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

cumprod
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 0 0 0 0 0 0 0 0]

cumsum
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  3  6 10 15 21 28 36]

diagonal
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]

dump

dumps
[[0 1 2]
 [3 4 5]
 [6 7 8]]
b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xf

/var/folders/90/frsch0qx4nb6qc5hzm_jrvvr0000gn/T/ipykernel_1444/2643456438.py:62: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  b = method()


In [31]:
a = np.array(np.arange(24).reshape(2, 3, 4))
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
np.ravel(a)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])